version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./docker/etc/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - .:/var/www
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    ports:
        - "3306:3306"
    volumes:
        - .data/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
    command: mysqld --sql_mode=""
    networks:
        - app-network

  phpmyadmin:
    platform: linux/amd64
    image: phpmyadmin/phpmyadmin
    environment:
        - PMA_ARBITRARY=0
        - PMA_HOST=mysql
        - PMA_PORT=3306
        - PMA_USER=root
        - PMA_PASSWORD=root
    restart: unless-stopped
    ports:
        - "8888:80"
    volumes:
        - /sessions
    networks:
        - app-network

networks:
  app-network:
    driver: bridge
